/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bannhaccu.view.quanly;

import com.bannhaccu.dao.HangDAO;
import com.bannhaccu.dao.SanPhamDAO;
import com.bannhaccu.dao.TheLoaiDAO;
import com.bannhaccu.model.Hang;
import com.bannhaccu.model.NhanVien;
import com.bannhaccu.model.SanPham;
import com.bannhaccu.model.TheLoai;
import java.awt.Window;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author TienAnh
 */
public class NvqlTaoMoiSanPham extends javax.swing.JFrame {
    private SanPhamDAO spDAO;
    private HangDAO hangDAO;
    private TheLoaiDAO tlDAO;
    private NhanVien nv;
    ArrayList<Hang> arr_data_hang;
    ArrayList<TheLoai> arr_data_tl;
    /**
     * Creates new form NvqlTaoMoiUser
     */
    public NvqlTaoMoiSanPham(NhanVien nv) {
        initComponents();
        spDAO = new SanPhamDAO();
        hangDAO = new HangDAO();
        tlDAO = new TheLoaiDAO();
        this.nv = nv;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initComboBox();
    }
    
    private void initComboBox () {
        // Init the loai combobox
        arr_data_tl = tlDAO.gelAllTheLoai();
        for (TheLoai item : arr_data_tl) { cbTheLoai.addItem(item.getTen()); }
        
        // Init Hang combobox
        arr_data_hang = hangDAO.gelAllHang();
        for (Hang item : arr_data_hang) { cbHang.addItem(item.getTen()); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbHang = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfThongsokithuat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfMota = new javax.swing.JTextArea();
        cbTheLoai = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Tạo mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên");

        jLabel2.setText("Thống số kĩ thuật");

        jLabel3.setText("Mô tả");

        jLabel4.setText("Thể loại");

        jLabel5.setText("Giá");

        jLabel6.setText("Hãng");

        tfThongsokithuat.setColumns(20);
        tfThongsokithuat.setRows(5);
        jScrollPane1.setViewportView(tfThongsokithuat);

        tfMota.setColumns(20);
        tfMota.setRows(5);
        jScrollPane2.setViewportView(tfMota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfName)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbHang, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfGia)
                                    .addComponent(cbTheLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tfName.getText().equals("") || tfThongsokithuat.getText().equals("")  || tfGia.getText().equals("")  || tfMota.getText().equals("")) { JOptionPane.showMessageDialog(null, "Không được để trống các trường"); return;}
        
        int id_tl = 0;
        String mota = "";
        for (TheLoai item : arr_data_tl) {
            if (item.getTen().equals(cbTheLoai.getSelectedItem().toString())){
                id_tl = item.getId();
                mota = item.getMota();
                break;
            }
        }
        TheLoai tl = new TheLoai(id_tl, cbHang.getSelectedItem().toString(), mota);
        
        int id_hang = 0;
        mota = "";
        for (Hang item : arr_data_hang) {
            if (item.getTen().equals(cbHang.getSelectedItem().toString())){
                id_hang = item.getId();
                mota = item.getMota();
                break;
            }
        }
        Hang hang = new Hang(id_hang, cbHang.getSelectedItem().toString(), mota);
        
        
        SanPham sp = new SanPham(
            -1, 
            tfName.getText(), 
            tfThongsokithuat.getText(),
            tfMota.getText(),
            0,
            new Float(tfGia.getText()), 
            "", hang, tl);

        boolean result = spDAO.storeSanpham(sp);
        if (result){
            JOptionPane.showMessageDialog(null, "Taọ sản phẩm thành công");
            Arrays.asList(Window.getWindows()).forEach(e -> e.dispose());
        new NvqlQuanLySanPham(this.nv).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Lỗi bất ngờ");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbHang;
    private javax.swing.JComboBox<String> cbTheLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfGia;
    private javax.swing.JTextArea tfMota;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextArea tfThongsokithuat;
    // End of variables declaration//GEN-END:variables
}
