/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bannhaccu.view.quanly;

import com.bannhaccu.dao.SanPhamDuocNhapKhoDAO;
import com.bannhaccu.model.PhieuNhapKho;
import com.bannhaccu.model.SanPhamDuocNhapKho;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class NvqlPhieuNhapKhoChiTiet extends javax.swing.JFrame {
    SanPhamDuocNhapKhoDAO spdnkDAO;
    /**
     * Creates new form NvqlPhieuNhapKhoChiTiet
     */
    public NvqlPhieuNhapKhoChiTiet(int id_npk) {
        initComponents();
        spdnkDAO = new SanPhamDuocNhapKhoDAO();
        initTable(id_npk);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void initTable(int id_pnk) {
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableSanpham.setDefaultRenderer(String.class, centerRenderer);
        tableSanpham.setDefaultRenderer(Double.class, centerRenderer);
        tableSanpham.setDefaultRenderer(Integer.class, centerRenderer);

        DefaultTableModel table = (DefaultTableModel) tableSanpham.getModel();
        ArrayList<SanPhamDuocNhapKho> arr_data = spdnkDAO.getListSanPhamNhapKho(id_pnk);

        int index = 0;
        DecimalFormat formatter = (DecimalFormat) NumberFormat.getInstance(Locale.US);
        formatter.applyPattern("#,###,###,###");
        for (SanPhamDuocNhapKho item : arr_data) {
            Object[] emptyData = {null, null, null, null, null, null};
            table.addRow(emptyData);

            tableSanpham.getModel().setValueAt(index + 1, index, 0);
            tableSanpham.getModel().setValueAt(item.getSanpham().getId(), index, 1);
            tableSanpham.getModel().setValueAt(item.getSanpham().getTen(), index, 2);
            tableSanpham.getModel().setValueAt(formatter.format(item.getSanpham().getGia()).toString(), index, 3);
            tableSanpham.getModel().setValueAt(item.getSoluong(), index, 4);
            tableSanpham.getModel().setValueAt(formatter.format(item.getTongtien()).toString(), index++, 5);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableSanpham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableSanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Mã sản phẩm", "Tên", "Gia", "Số lượng nhập", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableSanpham);
        if (tableSanpham.getColumnModel().getColumnCount() > 0) {
            tableSanpham.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableSanpham.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSanpham;
    // End of variables declaration//GEN-END:variables
}
