/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bannhaccu.view.nhanvien;

import com.bannhaccu.dao.DAO;
import com.bannhaccu.dao.PhieuNhapKhoDAO;
import com.bannhaccu.dao.SanPhamDAO;
import com.bannhaccu.dao.SanPhamDuocNhapKhoDAO;
import com.bannhaccu.model.NhanVien;
import com.bannhaccu.model.SanPham;
import com.bannhaccu.model.SanPhamDuocNhapKho;
import java.awt.Window;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class NvbhNhapKhoChiTiet extends javax.swing.JFrame {
    private SanPhamDuocNhapKhoDAO spdnkDAO;
    private PhieuNhapKhoDAO phieuNhapKhoDAO;
    private SanPhamDAO sanPhamDAO;
    private NhanVien nv;
    private int id_pnk;

    /**
     * Creates new form NvbhNhapKhoChiTiet
     */
    public NvbhNhapKhoChiTiet(NhanVien  nv, int id_pnk) {
        initComponents();
        spdnkDAO = new SanPhamDuocNhapKhoDAO();
        phieuNhapKhoDAO = new PhieuNhapKhoDAO();
        sanPhamDAO = new SanPhamDAO();
        this.id_pnk = id_pnk;
        this.nv = nv;
        initTable(id_pnk);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void initTable(int id_pnk) {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tableSanpham.setDefaultRenderer(String.class, centerRenderer);
        tableSanpham.setDefaultRenderer(Double.class, centerRenderer);
        tableSanpham.setDefaultRenderer(Integer.class, centerRenderer);

        DefaultTableModel table = (DefaultTableModel) tableSanpham.getModel();
        ArrayList<SanPhamDuocNhapKho> arr_data = spdnkDAO.getListSanPhamNhapKho(id_pnk);

        int index = 0;
        for (SanPhamDuocNhapKho item : arr_data) {
            Object[] emptyData = {null, null, null, null, null, null};
            table.addRow(emptyData);

            DecimalFormat formatter = (DecimalFormat) NumberFormat.getInstance(Locale.US);
            formatter.applyPattern("#,###,###,###");
            tableSanpham.getModel().setValueAt(index + 1, index, 0);
            tableSanpham.getModel().setValueAt(item.getSanpham().getId(), index, 1);
            tableSanpham.getModel().setValueAt(item.getSanpham().getTen(), index, 2);
            tableSanpham.getModel().setValueAt(formatter.format(item.getSanpham().getGia()).toString(), index, 3);
            tableSanpham.getModel().setValueAt(item.getSoluong(), index++, 4);
        }

        // Set default focus when init
        tableSanpham.setRequestFocusEnabled(true);
        tableSanpham.setRowSelectionInterval(0, 0);
        tableSanpham.setColumnSelectionInterval(5, 5);
        tableSanpham.editCellAt(0, 5);
        tableSanpham.requestFocus();
        
        // Handle fill các thông tin trống
        table.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                try{
                    if (table.getValueAt(e.getLastRow(), e.getColumn()) != null && new Integer(table.getValueAt(e.getLastRow(), e.getColumn())+"") > new Integer(table.getValueAt(e.getLastRow(), 4)+"")) {
                        JOptionPane.showMessageDialog(null, "Số lượng thực tế <= Số lượng nhập");
                        table.setValueAt(null, e.getLastRow(), e.getColumn());
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Số lượng thực tế phải là số nguyên dương");
                    table.setValueAt(null, e.getLastRow(), e.getColumn());
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSanpham = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableSanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Mã sản phẩm", "Tên", "Gia", "Số lượng nhập", "Thực tế nhận"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableSanpham);
        if (tableSanpham.getColumnModel().getColumnCount() > 0) {
            tableSanpham.getColumnModel().getColumn(0).setMinWidth(40);
            tableSanpham.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableSanpham.getColumnModel().getColumn(0).setMaxWidth(40);
            tableSanpham.getColumnModel().getColumn(1).setMinWidth(80);
            tableSanpham.getColumnModel().getColumn(1).setPreferredWidth(80);
            tableSanpham.getColumnModel().getColumn(1).setMaxWidth(80);
            tableSanpham.getColumnModel().getColumn(3).setMinWidth(120);
            tableSanpham.getColumnModel().getColumn(3).setPreferredWidth(120);
            tableSanpham.getColumnModel().getColumn(3).setMaxWidth(120);
            tableSanpham.getColumnModel().getColumn(4).setMinWidth(80);
            tableSanpham.getColumnModel().getColumn(4).setPreferredWidth(80);
            tableSanpham.getColumnModel().getColumn(4).setMaxWidth(80);
            tableSanpham.getColumnModel().getColumn(5).setMinWidth(80);
            tableSanpham.getColumnModel().getColumn(5).setPreferredWidth(80);
            tableSanpham.getColumnModel().getColumn(5).setMaxWidth(80);
        }

        jButton1.setText("Xác nhận nhập kho");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (int i = 0; i < tableSanpham.getModel().getRowCount(); i++) {
            if (tableSanpham.getModel().getValueAt(i, 5) == null) {
                JOptionPane.showMessageDialog(null, "Xác nhận thực nhận");
                return;
            }
        }
        try {
            // Bắt đầu transaction
            DAO.getConn().setAutoCommit(false);
            // 1. Update ischeck + Thực nhận
            phieuNhapKhoDAO.updateIsCheck(id_pnk);
            // 2. Update thuc nhan
            spdnkDAO.updateThucNhan(tableSanpham.getModel(), id_pnk);
            // 3. Cap nhat soluong sanpham
            sanPhamDAO.updateSoluong(tableSanpham.getModel());
            // Commit transaction
            DAO.getConn().commit();
            JOptionPane.showMessageDialog(null, "Nhập kho thành công");
            this.dispose();
            Arrays.asList(Window.getWindows()).forEach(e -> e.dispose());
            new NvbhNhapkho(nv).setVisible(true);
        } catch (Exception ex) {
            try {
                // Rollback transaction
                DAO.getConn().rollback();
            } catch (SQLException ex1) {
                Logger.getLogger(NvbhNhapKhoChiTiet.class.getName()).log(Level.SEVERE, null, ex1);
            }
            Logger.getLogger(NvbhNhapKhoChiTiet.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSanpham;
    // End of variables declaration//GEN-END:variables
}
